### ISSUE TITLE
TBC branch

### ISSUE THREAD

**Issue by Birkenstack** [Nixxen/TrinketMenu#16]
not necessary, but a tbc branch would be awesome to keep using this addon. cheers

**Comment by AreNaught** [comment]
Message: Interface\AddOns\TrinketMenu\TrinketMenuOpt.lua:59: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Thu May 20 11:32:12 2021
Count: 1
Stack: Interface\AddOns\TrinketMenu\TrinketMenuOpt.lua:59: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "=[C]"]: in function `SetBackdropBorderColor'
[string "@Interface\AddOns\TrinketMenu\TrinketMenuOpt.lua"]:59: in function `InitOptions'
[string "@Interface\AddOns\TrinketMenu\TrinketMenu.lua"]:307: in function `Initialize'
[string "@Interface\AddOns\TrinketMenu\TrinketMenu.lua"]:431: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by anis-moubarik** [comment]
I fixed this for TBC, you can find the release here https://github.com/anis-moubarik/TrinketMenu/releases/tag/1.13.4.5

**Comment by anis-moubarik** [comment]
Hey, I made a TBC patched TM, which you can download from here https://github.com/anis-moubarik/TrinketMenu/releases/tag/1.13.4.4-Classic

**Comment by Nixxen** [comment]
Great stuff @anis-moubarik.
Make a pull request and I'll have it added to the master.

**Comment by anis-moubarik** [comment]
I will, I'm not just 100% sure if this will somehow interfere with Vanilla Classic. Did they update the client there too? There's also Interface bump in the toc file.

**Comment by Nixxen** [comment]
Ah, I assumed it worked in both. I am not able to play currently, so unable to troubleshoot the addons.
There are some checks for flying in TBC at least that do not exist in classic, but based on their "rework" of the API for classic, I got the impression that they wanted to run both Classic and Retail (at the time, now also CTBC) on the same code base to limit the amount of individual issues they had to fix.

I haven't had time to neither play nor troubleshoot the past year, so could be things have changed.

Suppose I could make a unique TBC branch just to be sure. You'd have to fork from that TBC branch though, since git won't allow pull reqs. from something that does not share a common ancestor.

**Comment by anis-moubarik** [comment]
Reading from here https://github.com/Stanzilla/WoWUIBugs/wiki/2.5.1-Consolidated-UI-Changes and here https://github.com/Stanzilla/WoWUIBugs/issues/68#issuecomment-830351390, it seems you can make two toc (-BCC.toc and normal -Classic.toc) files and make them reference two sets of files, I can try and work this as I have both clients installed.

**Comment by anis-moubarik** [comment]
PR here https://github.com/Nixxen/TrinketMenu/pull/18

**Comment by Nixxen** [comment]
PR approved. Please report back if there are any issues.

**Comment by Nixxen** [comment]
Since there have been no reported issues, I'm closing this.
If there are any problems, please make a new issue :)
