### ISSUE TITLE
Hunter Feign Death

### ISSUE THREAD

**Issue by philomathikus** [Nixxen/TrinketMenu#5]
Hi,

Does this work with hunter feign death trinket swap based on queue? 

Thanks,

Max

**Comment by Nixxen** [comment]
Heya!

The manual swap queue works with feign death, but the automated queue does not work (as in the one you can set up in advance and it rotates trinkets).

**Comment by philomathikus** [comment]
Hi Nixxen,

Thank you for the reply! I would be happy to donate if you can make that work :) 

Best,

Max

**Comment by philomathikus** [comment]
I also just tried it for the first time (had the original TrinketMenu installed) and had the pet on a mob, attacked the mob with range myself, used a CD trinket, manually queued the next one, FD and it didn't swap... 

Isn't it meant to swap?

**Comment by Nixxen** [comment]
It is meant to swap. I did a test just now VS some wolves in AV to make sure nothing had broken that I hadn't noticed and it still works for me.
That said, classic FD is temperamental at best.
I've had times where it triggers the switch, but I'm put back into combat (the trigger should only trigger if you can actually switch the trinket, so out of combat). If this happens you'll get a "Can't do that in combat" message. The addon tried to switch as soon as you dropped combat but missed the window.
This is usually due to spell-batching, and you're almost instantly put into combat when it drops.

As for the automated queue I would need to find the time to work on it.
It's only a small hobby I do for fun in between work and several other projects.

**Comment by philomathikus** [comment]
I just tried it and the issue seems to be that if my pet is still attacking, it will not drop me out of combat... Not sure if this is a bug or a feature by Blizzard. 

I can make the same macro for freezing traps (just without the trap part): 

#showtooltip Freezing Trap
/petpassive
/petfollow
/stopattack
/cast [combat] Feign Death;

Will have to try a couple more options in the next couple of days.

**Comment by Nixxen** [comment]
Oh yeah! You'll need to have the pet stop attacking. Even then it sometimes batches an attack in and you get put back in combat. I think this might be the enemy attacking, but honestly I'm not 100% sure.

The absolute best way to prevent unfortunate batching is to passive pet beforehand, stop yourself from attacking then FD, but your mileage may vary as they say.
Sometimes it works when using pet passive in the same macro. Sometimes it batches.

My own FD macro is similar to yours BTW.
```
#showtooltip Feign Death
/petpassive [combat]
/cast [combat] Feign Death
```
